name: ntt
channels:
    - conda-forge
    - bioconda
dependencies:
    - snakemake
    - r-signac>=1.7.0
    - r-seurat
    - r-hdf5r
    - r-ggtern
    - r-rcolorbrewer
    - r-dplyr
    - salmon
    - biopython
    - pysam
    - sinto>=0.8.0
    - awscli
    - bwa-mem2
    - deeptools
    - bedtools
    - htslib
    - macs2
    - ucsc-bedgraphtobigwig
    - bioconductor-ensdb.hsapiens.v86
    - bioconductor-bsgenome.hsapiens.ucsc.hg38
    - bioconductor-biovizbase
    - bioconductor-fishpond
    - bioconductor-tximport
    - r-recommended
    - r-curl
    - hdf5
    - bcftools
    - cutadapt
    - pigz
